# frozen_string_literal: true

### Given a set of MARC records, and a CSV file with a set of proposed Korean fields,
###  add the Korean fields and output the records.
###  - CSV rows should have the format "MMS_ID,tag,roman_field,korean_field".
###  - An 880 is added for each Korean field, and a $6 in the corresponding roman field.
###  - Parentheical notes in 245a are removed and moved to a 500 field.
###  - A 588 field is added indicating the Korean data was generated by ChatGPT.

require_relative '../lib/lsp-data'
require 'CSV'

# Extract parenthetical translation note fro 245a
def get_translation_note(title_field)
  m = title_field.match(/ [(\[]([^)]*)[\])]\p{P}*$/)
  m ? m[1] : nil
end

# Generate a field wit the translation note removed, and linkage added.
#  'tagset' is the main and parallal tags in that order, e.g. ['245','880'] for the
#  main title field, and ['880','245'] for the parallel title field.
def generate_field(tagset, seqno, indicators, field_content, translation_note)
  subfields = generate_subfields(tagset[1], seqno, field_content)

  new_field = MARC::DataField.new(tagset[0], indicators[0], indicators[1], *subfields)
  return new_field unless tagset.include?('245') && translation_note

  new_field['a'].sub!(/ [(\[]#{Regexp.escape(translation_note)}[\])]([\s\p{P}]*)$/, '\1')
  new_field
end

# Generate an array of subfields, starting with the $6 linkage.
def generate_subfields(parallel_tag, seqno, field_content)
  linkage = "$6#{parallel_tag}-#{seqno}" + (parallel_tag == '880' ? '' : '/{dollar}1')
  field_content = "#{linkage}#{field_content}"
  subfields = field_content.split('$').filter { |sf| sf.length.positive? }
  subfields.map { |sf| [sf[0], sf[1..].sub('{dollar}', '$')] }
end

# Generate 500 field with translation note.
def generate_translation_field(translation_note)
  translation_field = MARC::DataField.new('500', ' ', ' ')
  translation_field.append(MARC::Subfield.new('a', "Title in translation: #{translation_note}."))
  translation_field
end

# Generate 588 field with ChatGPT note.
def generate_chatgpt_field
  chatgpt_note = MARC::DataField.new('588', '0', ' ')
  chatgpt_note.append(MARC::Subfield.new('a', "Non-Roman scripts were generated with OpenAI GPT-5.4 \
                                              and added following staff review, \
                                              #{Time.now.strftime('%B')} #{Time.now.year}."))
  chatgpt_note.append(MARC::Subfield.new('5', 'NjP'))
  chatgpt_note
end

# Detect potential conflicts that could prevent applying the change.
def check_conflicts(record, tag, roman_content)
  mms_id = record['001'].value
  return "Field #{tag} not found in record #{mms_id}.\n" unless record[tag]

  matched_fields = record.fields(tag).select { |f| f.to_s[7..].strip == roman_content }
  return "No field with tag #{tag} and content '#{roman_content}' found in record #{mms_id}.\n" if matched_fields.empty?
  return "Multiple instances of '#{tag} #{roman_content}' found in record #{mms_id}.\n" if matched_fields.length > 1
  return "#{tag} #{roman_content} already has a $6.\n" if matched_fields[0]['6']

  ''
end

input_dir = ENV.fetch('DATA_INPUT_DIR', nil)
output_dir = ENV.fetch('DATA_OUTPUT_DIR', nil)

update_file = "#{input_dir}/cotsen_korean_updates.csv"
all_updates = CSV.read(update_file)

records_file = "#{input_dir}/cotsen_korean.marcxml"

marc_reader = MARC::XMLReader.new(records_file, parser: 'magic', ignore_namespace: true)
marc_writer = MARC::XMLWriter.new("#{output_dir}/cotsen_korean_updated.marcxml")
marc_reader.each do |record|
  seqno = 99
  translation_note = get_translation_note(record['245']['a'])
  record_updates = all_updates.filter { |row| row[0] == record['001'].value }
  record_updates.each do |row|
    tag, roman_content, korean_content = row[1..3]
    # If there is a pontential conflict, print a message to stderr and skip that row.
    conflict = check_conflicts(record, tag, roman_content)
    $stderr.print conflict if conflict != ''
    next if conflict != ''

    matched_fields = record.fields(tag).select { |f| f.to_s[7..].strip == roman_content }
    indicators = "#{matched_fields[0].indicator1}#{matched_fields[0].indicator2}"
    new_roman_field = generate_field([tag, '880'], seqno, indicators, matched_fields[0].to_s[7..], translation_note)
    new_korean_field = generate_field(['880', tag], seqno, indicators, korean_content, translation_note)
    record = MarcCleanup.replace_fields(
      field_array: [{ source_field: matched_fields[0], replacement_field: new_roman_field,
                      ignore_indicators: false }],
      record: record
    )
    record << new_korean_field
    seqno -= 1
  end

  record << generate_translation_field(translation_note) if translation_note
  record << generate_chatgpt_field

  record = MarcCleanup.fix_f880(record)
  record = MarcCleanup.field_sort(record)
  marc_writer.write(record)
end
marc_writer.close
